### ISSUE TITLE
[Feature Request] Table view

### ISSUE THREAD

**Issue by broofa** [nikrolls/json-formatter#22]
When the top-level JSON structure is an Array, it would be helpful (at times) to present the data in table form.  Obviously this may problematic where complex structures are concerned (array of objects of objects of arrays... or whatever), but in many cases this would be helpful.

This request would add a "Table" View to the existing "Raw" and "Parsed" options.  Initially, this option would only be available in two cases:
* Array of simple Objects: Data would be represented as a table with object keys as column headings.
* Array of simple Arrays:  Similar to the above, but without column headings.
In both cases, if there are more than... say... 20 key-values / values in sub objects, the "Table" option would be disabled.

@nikrolls I can take a stab at this, but as it's a non-trivial amount of work so I thought I'd run the idea by you first to make sure you're open to it.

**Comment by nicole-ashley** [comment]
@broofa Great idea! That would be really useful. I'm happy for you to take the lead.

Most of my considerations are already answered with your MVP cases above, but I have a couple remaining:

* For usability, could we continue to show the Table button when not available but have it disabled with a tooltip explaining why?
* When rendering the table, what do we do about keys that aren't present in all objects? Do we create a column for them but leave cells blank where the key is missing, or do we omit those columns entirely?

**Comment by broofa** [comment]
Cool. I'll go ahead and start in on this.  No promises on when I'll have something up :-).  

Regarding your questions...
* Yes, table button should be present but disabled if (for whatever reason) a table isn't renderable.
* For sparsely defined keys there will be a column, with rows indicating where values are undefined.

**Comment by broofa** [comment]
@nikrolls Can you please review #23?  I don't mean to be pushy, but getting radio silence on that after your support for this idea here is a little... well... it'd be nice to see some movement there.

**Comment by broofa** [comment]
Closing due to lack of response on https://github.com/nikrolls/json-formatter/pull/23
